"""Building a position by hand, and refusing to lie about a bad one.

You are watching a game over someone's shoulder, or you have a board in front
of you.  There is no URL and no PGN -- there is a position.  So you place the
pieces, say whose move it is, and the engine tells you where you stand.

The whole difficulty is that most arrangements of pieces are not positions.
A board with two white kings, a pawn on the first rank, or Black in check
while White is to move cannot occur in a game, and an engine handed one will
either refuse to start or produce a confident number about nothing.  So
nothing here guesses: the arrangement is assembled into a FEN, python-chess's
own ``Board.status()`` judges it, and every flag it raises is turned into a
sentence saying what to fix.

Two details the app fills in rather than asking about, because getting them
wrong is silent and getting them right is mechanical:

**Castling rights.**  Only offered for a king and rook still on their home
squares.  A position with the white king on g1 has no castling rights to tick,
so the UI does not offer any, and a stale tick from a previous arrangement is
dropped rather than passed to the engine.

**En passant.**  Only offered where a double pawn push could actually just
have happened *and* a capture would be legal.  Candidates are generated by
building each possibility and asking python-chess whether the capture is
legal, rather than by reimplementing the rule -- there is one chess
implementation in this project and this is not a second one.
"""

from __future__ import annotations

import chess

#: The twelve pieces, as FEN letters. Anything else in an arrangement is a
#: bug in the caller rather than a user mistake, and is rejected as such.
SYMBOLS = "PNBRQKpnbrqk"

STARTING_PLACEMENT = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR"

#: One sentence per way an arrangement can fail, keyed by the flag
#: ``Board.status()`` raises. Phrased as what to do, not as what is wrong:
#: "add a white king" beats "STATUS_NO_WHITE_KING".
PROBLEMS = {
    chess.STATUS_EMPTY: "The board is empty. Place some pieces.",
    chess.STATUS_NO_WHITE_KING: "There is no white king. Every position needs one.",
    chess.STATUS_NO_BLACK_KING: "There is no black king. Every position needs one.",
    chess.STATUS_TOO_MANY_KINGS: "There is more than one king of a colour.",
    chess.STATUS_TOO_MANY_WHITE_PAWNS: "More than eight white pawns.",
    chess.STATUS_TOO_MANY_BLACK_PAWNS: "More than eight black pawns.",
    chess.STATUS_TOO_MANY_WHITE_PIECES: "More than sixteen white pieces.",
    chess.STATUS_TOO_MANY_BLACK_PIECES: "More than sixteen black pieces.",
    chess.STATUS_PAWNS_ON_BACKRANK: (
        "A pawn is on the first or last rank, where no pawn can stand."
    ),
    chess.STATUS_BAD_CASTLING_RIGHTS: (
        "The castling rights do not match where the kings and rooks are."
    ),
    chess.STATUS_INVALID_EP_SQUARE: (
        "That en-passant square could not have come from a double pawn push."
    ),
    chess.STATUS_OPPOSITE_CHECK: (
        "The side that is not to move is in check, which cannot happen -- "
        "either swap whose move it is, or move the attacked king."
    ),
    chess.STATUS_TOO_MANY_CHECKERS: (
        "Too many pieces are giving check at once for this to be a real position."
    ),
    chess.STATUS_IMPOSSIBLE_CHECK: (
        "This check could not have been delivered by any legal move."
    ),
}


class PositionError(ValueError):
    """An arrangement that cannot be turned into a position."""


def placement_from_map(pieces: dict) -> str:
    """``{"e1": "K", "e8": "k"}`` -> the FEN board field.

    Takes the shape the browser naturally has -- a square-to-piece map, which
    is what click-to-place produces -- rather than asking it to build FEN
    run-length encoding, which is where an off-by-one goes unnoticed.
    """
    board: dict[str, str] = {}
    for square, symbol in (pieces or {}).items():
        if square not in chess.SQUARE_NAMES:
            raise PositionError(f"{square!r} is not a square.")
        if symbol not in SYMBOLS:
            raise PositionError(f"{symbol!r} is not a piece.")
        board[square] = symbol

    rows = []
    for rank in range(8, 0, -1):
        row, empty = "", 0
        for file in "abcdefgh":
            symbol = board.get(f"{file}{rank}")
            if symbol is None:
                empty += 1
                continue
            if empty:
                row += str(empty)
                empty = 0
            row += symbol
        if empty:
            row += str(empty)
        rows.append(row or "8")
    return "/".join(rows)


def castling_options(placement: str) -> dict:
    """Which castling rights this arrangement could possibly have.

    Structural only: a king and a rook on their home squares. Whether the
    king has *actually* moved is not knowable from a position, which is why
    this is a list of what to offer rather than an answer.
    """
    try:
        board = chess.Board(f"{placement} w - - 0 1")
    except ValueError as exc:
        raise PositionError(f"That arrangement is not readable: {exc}") from exc

    def at(square: str, symbol: str) -> bool:
        piece = board.piece_at(chess.parse_square(square))
        return piece is not None and piece.symbol() == symbol

    white_king = at("e1", "K")
    black_king = at("e8", "k")
    return {
        "K": white_king and at("h1", "R"),
        "Q": white_king and at("a1", "R"),
        "k": black_king and at("h8", "r"),
        "q": black_king and at("a8", "r"),
    }


def en_passant_options(placement: str, turn: str) -> list[str]:
    """En-passant squares that could really be available here.

    Generated by building each candidate and asking python-chess about it, so
    the rule lives in one place. Only squares where a capture is genuinely
    available are offered -- an en-passant flag nobody can act on changes the
    FEN and nothing else, and would only ever be a source of confusion.

    Both checks are needed, and neither alone is enough.
    ``has_legal_en_passant`` asks whether a pawn *could capture onto* the
    square, and will happily say yes when there is no pawn there to take --
    it never looks for the victim. ``status`` is the one that checks a double
    push could have produced the square in the first place. Offering a square
    that passes only the first test hands the user a position the validator
    then rejects, for a reason they did not choose.
    """
    side = "w" if turn in ("w", "white") else "b"
    rank = 6 if side == "w" else 3
    found = []
    for file in "abcdefgh":
        square = f"{file}{rank}"
        try:
            board = chess.Board(f"{placement} {side} - {square} 0 1")
        except ValueError:
            continue
        if board.status() & chess.STATUS_INVALID_EP_SQUARE:
            continue
        if board.has_legal_en_passant():
            found.append(square)
    return found


def assemble(
    pieces: dict | str,
    *,
    turn: str = "w",
    castling: str = "",
    en_passant: str = "-",
    halfmove: int = 0,
    fullmove: int = 1,
) -> str:
    """An arrangement plus its details -> a FEN, with the details cleaned up.

    Castling rights that the arrangement cannot support and en-passant squares
    that could not have arisen are **dropped rather than rejected**: they are
    almost always left over from a previous arrangement, and failing the whole
    position over a stale tick box would be obtuse.
    """
    placement = pieces if isinstance(pieces, str) else placement_from_map(pieces)
    side = "w" if turn in ("w", "white") else "b"

    possible = castling_options(placement)
    rights = "".join(flag for flag in "KQkq"
                     if flag in (castling or "") and possible[flag])

    target = (en_passant or "-").strip() or "-"
    if target != "-" and target not in en_passant_options(placement, side):
        target = "-"

    return (f"{placement} {side} {rights or '-'} {target} "
            f"{max(0, int(halfmove))} {max(1, int(fullmove))}")


def describe(fen: str) -> dict:
    """Judge a position and say, in sentences, what is wrong with it.

    ``valid`` means an engine can be handed this. ``problems`` is empty when it
    is, and otherwise lists every reason. ``gameOver`` is not a problem but is
    worth saying out loud: an arranged checkmate has no evaluation to give.
    """
    try:
        board = chess.Board(fen)
    except ValueError as exc:
        return {"fen": fen, "valid": False, "problems": [str(exc)],
                "gameOver": False, "outcome": None, "check": False,
                "turn": "white", "material": None}

    status = board.status()
    problems = [message for flag, message in PROBLEMS.items() if status & flag]
    if status and not problems:
        # A flag we have no sentence for: say so honestly rather than
        # pretending the position is fine.
        problems.append(f"The position is not legal (status {status}).")

    outcome = board.outcome(claim_draw=True) if not status else None
    return {
        "fen": board.fen(),
        "valid": not problems,
        "problems": problems,
        "turn": "white" if board.turn == chess.WHITE else "black",
        "check": bool(not status and board.is_check()),
        "gameOver": outcome is not None,
        "outcome": _outcome_text(board, outcome),
        "material": _material(board) if not status else None,
        "castling": castling_options(board.board_fen()),
        "enPassantOptions": en_passant_options(
            board.board_fen(), "w" if board.turn == chess.WHITE else "b"),
    }


def _outcome_text(board: chess.Board, outcome) -> str | None:
    if outcome is None:
        return None
    if board.is_checkmate():
        winner = "White" if outcome.winner == chess.WHITE else "Black"
        return f"Checkmate -- {winner} has already won, so there is nothing to evaluate."
    if board.is_stalemate():
        return "Stalemate -- the side to move has no legal move and is not in check."
    if board.is_insufficient_material():
        return "Neither side has enough material to mate."
    return f"The game is already over ({outcome.result()})."


def _material(board: chess.Board) -> dict:
    values = {chess.PAWN: 1, chess.KNIGHT: 3, chess.BISHOP: 3,
              chess.ROOK: 5, chess.QUEEN: 9}
    counts = {}
    for colour, name in ((chess.WHITE, "white"), (chess.BLACK, "black")):
        counts[name] = sum(len(board.pieces(kind, colour)) * value
                           for kind, value in values.items())
    counts["diff"] = counts["white"] - counts["black"]
    return counts


__all__ = [
    "PROBLEMS",
    "STARTING_PLACEMENT",
    "SYMBOLS",
    "PositionError",
    "assemble",
    "castling_options",
    "describe",
    "en_passant_options",
    "placement_from_map",
]
